---
title: "EDS 223- Discussion 5"
author: "Josephine Cardelle"
format: html
editor_options: 
  chunk_output_type: console
---

# Load libraries and read in data
```{r}
library(tidyverse)
library(sf)
library(terra)
library(spData)
library(spDataLarge)
```

```{r}
# Load raster data representing grain sizes with the three classes clay, silt and sand
grain <- terra::rast(system.file("raster/grain.tif", package = "spData"))
```

```{r}
#Subset points higher than 3100 meters in nz_height (from spData) and create a template raster with rast(), where the resolution is 3 km x 3 km for the extent of the subset dataset

nz_height_3100 <- nz_height %>% 
  dplyr::filter(elevation > 3100)

# Template
nz_template <- rast(terra::ext(nz_height_3100), 
                    resolution = 3000, 
                    crs = terra::crs(nz_height_3100))

```

```{r}
# Count numbers of the highest points in each grid cell
nz_raster <- rasterize(nz_height_3100, nz_template, field = "elevation", fun = "length")

plot(nz_raster, main = "Number of Elevation Points > 3100 in Each Grid Cell")
plot(st_geometry(nz_height_3100), add = TRUE)

# Find the maximum elevation in each grid cell
nz_raster2 <- rasterize(nz_height_3100, nz_template, field = "elevation", fun = max)

plot(nz_raster2, main = "Maximum Elevation in Each Grid Cell ")
plot(st_geometry(nz_height_3100), add = TRUE)
```

```{r}
# Aggregate the raster that counts the highest points in New Zealand/Aotearoa
# Reduce its geographic resolution by half, such that cells are 6 x 6 km
# Plot the result
# Resample back to the original resolution of 3 km x 3 km

# Reduce the resolution by combining 2 cells in each direction into larger cells
# Sum the values of all cells for the resulting elevation value
nz_raster_low <- aggregate(nz_raster, fact = 2, fun = sum, na.rm = TRUE)

# Convert the new raster's resolution back to the 3kmx3km resolution of original raster
nz_resample <- resample(nz_raster_low, nz_raster)

plots <- c(nz_raster, nz_resample)
labs <- c("Original 6 x 6 km", "Resample 6 x 6 km")
plot(plots, main = labs)

plot(nz_raster_low, main = "Resample 3 x 3 km")
```

```{r}
# Convert raster data to polygon vector data
grain_poly <- as.polygons(grain) %>% 
  st_as_sf()

plot(grain, main = "Grain (Raster)")

plot(grain_poly, main = "Grain (Vector)")

# Subset polygons to only clay
clay <- grain_poly %>% 
  dplyr::filter(grain == "clay")

plot(clay, main = "Clay")
```

